language: bash

services: docker

env:
  - VERSION=1.6

before_script:
  - env | sort
  - cd "${VERSION}"
  - IMAGE="schroedan/ng:${VERSION}"

script:
  - travis_retry docker build -t "$IMAGE" .

after_script:
  - docker images
