language: bash

services: docker

env:
  - VERSION=1.6
  - VERSION=6.2
  - VERSION=7.0
  - VERSION=7.1
  - VERSION=7.2
  - VERSION=7.3

before_script:
  - env | sort

script:
  - travis_retry make

after_script:
  - docker images
