#!/bin/sh

set -e

# We need to test if /var/run/dbus exists, since script will fail if it does not
[ ! -e /var/run/dbus ] && mkdir /var/run/dbus

/usr/bin/dbus-daemon --system

if [ "$2" == "test" ] || [ "$2" == "e2e" ]; then
    printf "Starting Xvfb"
    /usr/bin/Xvfb ${DISPLAY} -screen 0 ${GEOMETRY} & XVFBPID=$!

    tries=10
    while [ $tries -gt 0 ]; do
        tries=$(( $tries - 1 ))
        printf "."
        if kill -0 ${XVFBPID} 2>/dev/null; then
            printf "\n"
            break
        else
            sleep 1
            continue
        fi
        printf "\n"
        printf "Xvfb failed to start\n" >&2
        exit 1
    done
fi

exec "$@"
